#################################
## Chart overrides
#################################

# Global overrides
global:
  baseDomain:
  tlsSecret:
  acme: false

astronomer:
  orbit:
    resources: {}

  houston:
    resources: {}

  commander:
    resources: {}

  registry:
    resources: {}

nginx:
  resources: {}
  loadBalancerIP:
  loadBalancerSourceRanges:

grafana:
  resources: {}

prometheus:
  resources: {}
