{{ define "grafana_image" -}}
{{ .Values.images.grafana.name }}:{{ or .Values.global.imageTag .Values.images.grafana.tag }}
{{- end }}

{{ define "grafana_url" -}}
grafana.{{ .Values.global.baseDomain }}
{{- end }}

{{ define "db_bootstrapper_image" -}}
{{ .Values.images.dbBootstrapper.name }}:{{ or .Values.global.imageTag .Values.images.dbBootstrapper.tag }}
{{- end }}
