################################
## Airflow StatsD Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-statsd
  labels:
    tier: airflow
    component: statsd
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: {{ .Values.ports.statsdScrape }}
spec:
  type: NodePort
  selector:
    tier: airflow
    component: statsd
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
  ports:
    - name: statsd-ingest
      protocol: UDP
      port: {{ .Values.ports.statsdIngest }}
      targetPort: {{ .Values.ports.statsdIngest }}
    - name: statsd-scrape
      protocol: TCP
      port: {{ .Values.ports.statsdScrape }}
      targetPort: {{ .Values.ports.statsdScrape }}
