################################
## Prometheus StatefulSet
#################################
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: "{{ .Release.Name }}-prometheus"
  labels:
    tier: monitoring
    component: prometheus
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: monitoring
      component: prometheus
      release: {{ .Release.Name }}
      workspace: {{ .Values.workspace }}
  template:
    metadata:
      labels:
        tier: monitoring
        component: prometheus
        release: {{ .Release.Name }}
        workspace: {{ .Values.workspace }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/prometheus-configmap.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      serviceAccountName: "{{ .Release.Name }}-prometheus"
      securityContext:
        runAsUser: 2000
        fsGroup: 1000
      containers:
        - name: "{{ .Release.Name }}-prometheus"
          image: {{- include "prometheus_image" . | indent 1 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          args:
            - "--config.file=/etc/prometheus/config/prometheus.yaml"
            - "--storage.tsdb.path={{ .Values.dataDir }}"
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/config
          {{- if .Values.persistence.enabled }}
            - name: prometheus-data-volume
              mountPath: "{{ .Values.dataDir }}"
          {{- end }}
          ports:
            - name: prometheus-data
              containerPort: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: /graph
              port: {{ .Values.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /graph
              port: {{ .Values.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: "{{ .Release.Name }}-prometheus"
            items:
              - key: prometheus.yaml
                path: prometheus.yaml
  {{- if not .Values.persistence.enabled }}
        - name: prometheus-data-volume
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: prometheus-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
      {{- end }}
  {{- end }}
