{{ define "helm_globals" -}}
  {{- $globals := dict -}}
  {{- $_ := set $globals "baseDomain" .Values.global.baseDomain -}}
  {{- $_ := set $globals "registryAuthSecret" .Values.global.registryAuthSecret -}}
  {{- $_ := set $globals "acme" (.Values.global.acme) -}}
  {{- $_ := set $globals "rbacEnabled" .Values.global.rbacEnabled -}}
  {{- $_ := set $globals "tlsSecret" (print .Values.global.tlsSecret | toString | replace "<nil>" "") -}}
  {{ $globals | toJson | print }}
{{- end }}

{{- define "random_string" }}
  {{- randAlphaNum 32 | b64enc }}
{{- end }}

{{ define "commander_image" -}}
{{ .Values.images.commander.name }}:{{ or .Values.global.imageTag .Values.images.commander.tag }}
{{- end }}

{{ define "houston_image" -}}
{{ .Values.images.houston.name }}:{{ or .Values.global.imageTag .Values.images.houston.tag }}
{{- end }}

{{ define "orbit_image" -}}
{{ .Values.images.orbit.name }}:{{ or .Values.global.imageTag .Values.images.orbit.tag }}
{{- end }}

{{ define "registry_image" -}}
{{ .Values.images.registry.name }}:{{ or .Values.global.imageTag .Values.images.registry.tag }}
{{- end }}

{{ define "db_bootstrapper_image" -}}
{{ .Values.images.dbBootstrapper.name }}:{{ or .Values.global.imageTag .Values.images.dbBootstrapper.tag }}
{{- end }}

{{ define "cli_install_image" -}}
{{ .Values.images.cliInstall.name }}:{{ or .Values.global.imageTag .Values.images.cliInstall.tag }}
{{- end }}

{{ define "registry_docker_config" -}}
  {{- $domain := printf "registry.%v" .Values.global.baseDomain }}
  {{- $email := printf "admin@%v" .Values.global.baseDomain }}
  {{- $user := randAlphaNum 16 -}}
  {{- $pass := randAlphaNum 32 -}}

  {{- $config := dict "auths" -}}
  {{- $auth := dict -}}
  {{- $data := dict -}}
  {{- $_ := set $data "username" $user -}}
  {{- $_ := set $data "password" $pass -}}
  {{- $_ := set $data "email" $email -}}
  {{- $_ := set $data "auth" (printf "%v:%v" $user $pass | b64enc) -}}
  {{- $_ := set $auth $domain $data -}}
  {{- $_ := set $config "auths" $auth -}}
  {{ $config | toJson | print }}
{{- end }}

{{ define "auth_strategies" -}}
  {{- if or .Values.auth.local.enabled -}}
    local,
  {{- end -}}
  {{- if or .Values.auth.google.enabled -}}
    google_oauth,
  {{- end -}}
  {{- if or .Values.auth.auth0.enabled -}}
    auth0_oauth,
  {{- end -}}
  {{- if or .Values.auth.github.enabled -}}
    github_oauth,
  {{- end -}}
{{- end }}
