################################
## Astronomer Ingress
#################################
{{- if .Values.global.baseDomain }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-public-ingress
  labels:
    component: public-ingress
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: {{ eq .Values.global.acme true | quote }}
spec:
  {{- if or .Values.global.tlsSecret .Values.global.acme }}
  tls:
  {{- if .Values.global.acme }}
    - secretName: astronomer-public-tls
  {{- end }}
  {{- if .Values.global.tlsSecret }}
    - secretName: {{ .Values.global.tlsSecret }}
  {{- end }}
      hosts:
        - houston.{{ .Values.global.baseDomain }}
        - registry.{{ .Values.global.baseDomain }}
        - app.{{ .Values.global.baseDomain }}
  {{- end }}
  rules:
  - host: houston.{{ .Values.global.baseDomain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-houston
            servicePort: houston-http
  - host: registry.{{ .Values.global.baseDomain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-registry
            servicePort: registry-http
  - host: app.{{ .Values.global.baseDomain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-orbit
            servicePort: orbit-http
  - host: install.{{ .Values.global.baseDomain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-cli-install
            servicePort: install-http
{{- end }}
