################################
## Install service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-install
  labels:
    tier: astronomer
    component: install
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    tier: astronomer
    component: install
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.ports.installHTTP }}
      targetPort: {{ .Values.ports.installHTTP }}
      protocol: TCP
      name: install-http
