# Default values for astronomer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# User in pilot containers
uid: 100

# Images for pilot
images:
  commander:
    name: astronomerinc/ap-commander
    tag: 0.4.1
  registry:
    name: astronomerinc/ap-registry
    tag: 0.4.1
  houston:
    name: astronomerinc/ap-houston-api
    tag: 0.4.1
  orbit:
    name: astronomerinc/ap-orbit-ui
    tag: 0.4.1
  dbBootstrapper:
    name: astronomerinc/ap-db-bootstrapper
    tag: 0.4.1
  cliInstall:
    name: astronomerinc/ap-cli-install
    tag: 0.4.1

# Astronomer platform config
data:
  houstonDatabaseSecret: "houston-database"
  airflowDatabaseSecret: "houston-database"

bootstrapDatabase: true

smtp:
  uri: ~

auth:
  local:
    enabled: true
  google:
    enabled: true
    clientId: ~
  auth0:
    enabled: true
    clientId: "rH2L4yKctlepniTyJW3MkuXuTreOHHn1"
    baseDomain: "astronomerio.auth0.com"
    externalLogin: false
  github:
    enabled: true

orbit:
  env: {}
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

houston:
  env: {}
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

commander:
  env: {}
  resources: {}
   # limits:
   #  cpu: 100m
   #  memory: 128Mi
   # requests:
   #  cpu: 100m
   #  memory: 128Mi

registry:
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

  persistence:
    # Enable persistent storage
    enabled: true
    # Size of volume to provision
    size: 50Gi
    # If using a custom storageClass, pass name ref to all statefulSets here
    storageClassName:

  auth:
    service: "docker-registry"
    issuer: "houston"

install:
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

ports:
  houstonHTTP: 8870
  commanderHTTP: 8880
  commanderGRPC: 50051
  orbitHTTP: 8080
  registryHTTP: 5000
  installHTTP: 80
