################################
## Airflow Worker StatefulSet
#################################
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    tier: airflow
    component: worker
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ .Release.Name }}-worker
  replicas: {{ .Values.workers.replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      tier: airflow
      component: worker
      release: {{ .Release.Name }}
      workspace: {{ .Values.workspace }}
  template:
    metadata:
      labels:
        tier: airflow
        component: worker
        release: {{ .Release.Name }}
        workspace: {{ .Values.workspace }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.workers.terminationGracePeriodSeconds }}
      securityContext:
        runAsUser: {{ .Values.uid }}
        fsGroup: {{ .Values.gid }}
      {{- if .Values.global.registryAuthSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registryAuthSecret }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-worker
          image: {{- include "airflow_image" . | indent 1 }}
          args: ["airflow", "worker"]
          resources:
{{ toYaml .Values.workers.resources | indent 12 }}
          ports:
            - name: worker-logs
              containerPort: {{ .Values.ports.workerLogs }}
          volumeMounts:
            - name: logs
              mountPath: /usr/local/airflow/logs
          env:
          {{- include "airflow_environment" . | indent 10 }}
        - name: {{ .Release.Name }}-worker-gc
          image: {{- include "airflow_image" . | indent 1 }}
          args: ["crond", "-f", "-d", "0"]
          volumeMounts:
            - name: logs
              mountPath: /usr/local/airflow/logs
{{- if not .Values.workers.persistence.enabled }}
      volumes:
        - name: logs
          emptyDir: {}
{{- else }}
  volumeClaimTemplates:
    - metadata:
        name: logs
      spec:
      {{- if .Values.workers.persistence.storageClassName }}
        storageClassName: {{ .Values.workers.persistence.storageClassName }}
      {{- end }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.workers.persistence.size }}
{{- end }}
